$primary = rgb({{ primary }})
$onPrimary = rgb({{ onPrimary }})
$secondary = rgb({{ secondary }})
$onSecondary = rgb({{ onSecondary }})
$background = rgb({{ background }})
$onBackground = rgb({{ onBackground }})
