[[mgr.prepend_keymap]]
on = "y"
run = [
    'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list',
    "yank",
]

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = "+"
run = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on = "-"
run = "plugin zoom -1"
desc = "Zoom out hovered file"

[[mgr.prepend_keymap]]
on = "<C-n>"
run = '''
    shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
'''

[[mgr.prepend_keymap]]
on = "<C-v>"
run = '''
    shell '~/.config/hypr/scripts/paste_file_to_yazi.sh $(pwd)'
'''
