$primary_paletteKeyColor = 777777
$secondary_paletteKeyColor = 767676
$tertiary_paletteKeyColor = 7a7777
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 777777
$background = 141414
$onBackground = e3e3e3
$surface = 141414
$surfaceDim = 141414
$surfaceBright = 393939
$surfaceContainerLowest = 0f0f0f
$surfaceContainerLow = 1c1c1c
$surfaceContainer = 202020
$surfaceContainerHigh = 2a2a2a
$surfaceContainerHighest = 353535
$onSurface = e3e3e3
$surfaceVariant = 474747
$onSurfaceVariant = c6c6c6
$inverseSurface = e3e3e3
$inverseOnSurface = 313131
$outline = 909090
$outlineVariant = 474747
$shadow = 000000
$scrim = 000000
$surfaceTint = c6c6c6
$primary = c6c6c6
$onPrimary = 303030
$primaryContainer = 474747
$onPrimaryContainer = e2e2e2
$inversePrimary = 5e5e5e
$secondary = c6c6c6
$onSecondary = 313131
$secondaryContainer = 494949
$onSecondaryContainer = e2e2e2
$tertiary = cac5c6
$onTertiary = 323031
$tertiaryContainer = 939090
$onTertiaryContainer = 000000
$error = e4beb9
$onError = 601410
$errorContainer = 891c18
$onErrorContainer = e2e2e2
$primaryFixed = e2e2e2
$primaryFixedDim = c6c6c6
$onPrimaryFixed = 1b1b1b
$onPrimaryFixedVariant = 474747
$secondaryFixed = e2e2e2
$secondaryFixedDim = c6c6c6
$onSecondaryFixed = 1c1c1c
$onSecondaryFixedVariant = 474747
$tertiaryFixed = e7e1e2
$tertiaryFixedDim = cac5c6
$onTertiaryFixed = 1d1b1c
$onTertiaryFixedVariant = 484646
$term0 = 343434
$term1 = eb5baf
$term2 = e5c4c7
$term3 = e5e5e5
$term4 = afa6bd
$term5 = cd9cb9
$term6 = e6c2af
$term7 = d8d8d8
$term8 = a3a3a3
$term9 = ed89bc
$term10 = e3dbdb
$term11 = f4f4f4
$term12 = c1c0c5
$term13 = dcb4c9
$term14 = e2d9d6
$term15 = ffffff
$rosewater = f1f1f1
$flamingo = e2e2e2
$pink = ebd7e2
$mauve = e2b1d8
$red = dfa2c4
$maroon = d7b6c5
$peach = e8c5d0
$yellow = f1f1f1
$green = e3dfde
$teal = e1dee6
$sky = e3d6e8
$sapphire = dbbde6
$blue = d8b0db
$lavender = e4c2e1
$klink = 9f7ba9
$klinkSelection = a07aa8
$kvisited = aa6ca0
$kvisitedSelection = ac6b9e
$knegative = cf61a4
$knegativeSelection = d061a1
$kneutral = ec8db7
$kneutralSelection = ec8eb3
$kpositive = ed9450
$kpositiveSelection = ed9450
$text = e3e3e3
$subtext1 = c6c6c6
$subtext0 = 909090
$overlay2 = 7e7d7d
$overlay1 = 6a6a6a
$overlay0 = 595959
$surface2 = 484848
$surface1 = 383838
$surface0 = 262626
$base = 141414
$mantle = 141414
$crust = 131313
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
