# windowrulev2 = opacity 0.8 0.7, match:class kitty
# windowrulev2 = opacity 0.95 0.85, match:class Code

windowrule = float on, match:class QQ
windowrule = center on, match:class QQ
windowrule = float on, match:class wechat
windowrule = center on, match:class wechat

windowrule = float on, match:class org.pulseaudio.pavucontrol
windowrule = center on, match:class org.pulseaudio.pavucontrol
windowrule = float on, match:class blueman-manager
windowrule = float on, match:class nm-connection-editor
windowrule = float on, match:class [Bb]top
windowrule = float on, match:class [Bb]top

windowrule = float on, match:class ranger
windowrule = float on, match:class vlc
windowrule = center on, match:class vlc
windowrule = float on, match:class mpv
windowrule = center on, match:class mpv
windowrule = float on, match:class qmmp
windowrule = center on, match:class qmmp
windowrule = float on, match:title musikcube
windowrule = center on, match:title musikcube

windowrule = float on, match:class org.kde.dolphin
windowrule = float on, match:class org.kde.ark

windowrule = float on, match:class org.gnome.Nautilus

windowrule = float on, match:class cmake-gui
windowrule = float on, match:class Watt Toolkit

# windowrule = noanim, match:class wofi
# windowrule = opacity 0.85 0.8, match:class wofi

windowrule = float on, match:class feh
windowrule = center on, match:class feh

windowrule = float on, match:class clash-verge
windowrule = center on, match:class clash-verge

windowrule = float on, match:class tlpui
windowrule = center on, match:class tlpui

windowrule = float on, match:class nwg-look
windowrule = center on, match:class nwg-look
windowrule = float on, match:class Lxappearance
windowrule = center on, match:class Lxappearance
windowrule = float on, match:class qt6ct
windowrule = center on, match:class qt6ct
windowrule = float on, match:class qt5ct
windowrule = center on, match:class qt5ct
windowrule = float on, match:class kvantummanager
windowrule = center on, match:class kvantummanager

windowrule = float on, match:class termfilechooser
windowrule = center on, match:class termfilechooser

windowrule = float on, match:title todo
windowrule = center on, match:title todo

windowrule = float on, match:title Yazi(.*)
windowrule = center on, match:title Yazi(.*)

windowrule = workspace 10, match:class wechat|QQ|clash-verge|Feishu
windowrule = workspace special:music, match:class feishin

windowrule = workspace 1, match:title atomclass
