#!/usr/bin/env bash

iDIR="$HOME/.config/swaync/icons/"
# Get brightness
# get_backlight() {
# 	LIGHT=$(printf "%.0f\n" $(brightnessctl i))
# 	echo "${LIGHT}%"
# }

# Get icons
get_icon() {
	backlight="$(brightnessctl g)"
	current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "9600") ]]; then
		echo "$iDIR/brightness-20.png" 
	elif [[ ("$current" -ge "9600") && ("$current" -le "19200") ]]; then
		echo "$iDIR/brightness-40.png" 
	elif [[ ("$current" -ge "19200") && ("$current" -le "28800") ]]; then
		echo "$iDIR/brightness-60.png" 
	elif [[ ("$current" -ge "28800") && ("$current" -le "38400") ]]; then
		echo "$iDIR/brightness-80.png" 
	elif [[ ("$current" -ge "38400") && ("$current" -le "48000") ]]; then
		echo "$iDIR/brightness-100.png" 
	fi
}

# Notify
# notify_user() {
# 	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $(brightnessctl g)"
# }
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Brightness : $(brightnessctl g)"
}

# Increase brightness
inc_backlight() {
	# brightnessctl set 2%+ && get_icon && notify_user
	brightnessctl set 2%+ && notify_user
}

# Decrease brightness
dec_backlight() {
	# brightnessctl set 2%- && get_icon && notify_user
	brightnessctl set 2%- && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
